### ISSUE TITLE
npm install on linux

### ISSUE THREAD

**Issue by chris-hranj** [bcoe/unitgen#1]
can't install this module via npm on unbuntu 14.04

**Comment by bcoe** [comment]
@chris-hranj what version of Node.js are you running, mind pasting the .npm-error logs?

**Comment by chris-hranj** [comment]
sorry for the vagueness of my issue, i was at a hackathon and stressed for time.
im using node version 0.10.33. im probably missing a dependency or something. the debug log is enormous and github doesnt let you attach log files, so here's this

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-39-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/brodan/Documents/Projects/Trillio/node_modules/unitgen/node_modules/speaker
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-39-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "unitgen"
npm ERR! node v0.10.33
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE

npm ERR! speaker@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the speaker@0.2.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/brodan/Documents/Projects/Trillio/npm-debug.log
